version: '1.0'
services:
  - name: db
    type: mariadb
    version: 10.4
    configuration: StandAlone
    username: ghost
    database: ghost
    # Ask password on create
    userPassword: null
    password: null
    ports:
      - 3306
    remoteAccess: false
    comments:
      userPassword: Password for user "ghost"
    deployTo:
      - ghost

  - name: ghost
    type: docker
    image: ghost
    version: 3
    ports:
      - 2368
    remoteAccess: false
    env:
      url: "http://{{=service('ghost').getNginxDomain()}}"
      database__client: mysql
      database__connection__host: "{{=service('db').getMasterAlias()}}"
      database__connection__user: "{{=service('db').get('username')}}"
      database__connection__password: "{{=service('db').get('userPassword')}}"
      database__connection__database: "{{=service('db').get('database')}}"
    deployTo:
      - ghost

  - name: pma
    type: docker
    image: phpmyadmin/phpmyadmin
    version: latest
    ports:
      - 80
    remoteAccess: false
    env:
      PMA_HOST: "{{=service('db').getMasterAlias()}}"
      PMA_PORT: "{{=service('db').getMainPort()}}"
    deployTo:
      - ghost

  - name: web
    type: nginx
    version: 1.17
    ports:
      - 80
      - 443
    remoteAccess: true
    serviceFiles:
      - name: ghost
      - name: pma
    deployTo:
      - ghost

hosts:
  - name: ghost
    requirements:
      cores: 1
      memory: 1
